// Generated by CoffeeScript 1.9.2
(function() {
  var NodeApp,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  NodeApp = require("../nodejs/NodeApp.js");

  this.ProjApp = (function(superClass) {
    extend(ProjApp, superClass);

    function ProjApp() {
      ProjApp.__super__.constructor.call(this);
    }

    return ProjApp;

  })(NodeApp);

  module.exports = this.ProjApp;

}).call(this);

//# sourceMappingURL=ProjApp.js.map
