// Generated by CoffeeScript 1.9.3
(function() {
  var NodeApp, sample_code,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  NodeApp = require("../../nodejs/NodeApp.js");

  this.NodeProjApp = (function(superClass) {
    extend(NodeProjApp, superClass);

    function NodeProjApp() {
      NodeProjApp.__super__.constructor.call(this);
      console.log("node proj start");
    }

    return NodeProjApp;

  })(NodeApp);

  sample_code = function() {

    /* nodejs function */
    this.server.start();
    this.csv_to_json([0, 1, 2, 3, 4, 5], "./data/test.csv", (function(_this) {
      return function(err, arr) {
        return console.log(arr);
      };
    })(this));
    this.readline_func("./contents/index.html", (function(_this) {
      return function(line) {
        return console.log(line);
      };
    })(this));
    this.jsdom_check("./contents/index.html", (function(_this) {
      return function(errors, _window) {
        var dom, word;
        if (errors) {
          throw errors;
        }
        dom = _window.$("title");
        word = "";
        dom.each(function(e) {
          return word += $(this).text() + "\n";
        });
        return console.log(word);
      };
    })(this));
    return this.check_dir_tree("./", /coffee$/, (function(_this) {
      return function(loc, file) {
        return console.log(loc);
      };
    })(this));
  };

  module.exports = this.NodeProjApp;

}).call(this);
