// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.ClientApp = (function(superClass) {
    extend(ClientApp, superClass);

    function ClientApp() {
      ClientApp.__super__.constructor.call(this);
      console.log("client app");
    }

    return ClientApp;

  })(this.NodeClient);

}).call(this);

//# sourceMappingURL=ClientApp.js.map
