// Generated by CoffeeScript 1.9.3
(function() {
  var Config;

  Config = (function() {
    function Config() {}

    Config.prototype.ignore_data_dir = "./ignore_data";

    Config.prototype.node_config_path = "ignore_data/node.cson";

    return Config;

  })();

  module.exports = Config;

}).call(this);
