// Generated by CoffeeScript 1.9.0
(function() {
  this.App = require("./contents/nodejs/App.js");

  this.a = new this.App();

  this.a.server.start();

}).call(this);

//# sourceMappingURL=nodeapp.js.map
