// Generated by CoffeeScript 1.9.2
(function() {
  this.App = require("./contents/proj/node/NodeProjApp.js");

  this.a = new this.App();

  this.a.server.start();

}).call(this);

//# sourceMappingURL=server.js.map
