// Generated by CoffeeScript 1.9.0
(function() {
  $((function(_this) {
    return function() {
      return _this.nc = new _this.NodeClient;
    };
  })(this));


  /*
  @perfectSquares = ->
  	num = 0
  	loop
  		num += 1
  		console.log num
  		yield num * num
  	return
  
  window.ps or= perfectSquares()
   */

}).call(this);

//# sourceMappingURL=main.js.map
