// Generated by CoffeeScript 1.9.2

/*
2015/02/11: goBackを使うと、wvが使えなくなる模様
 */

(function() {
  var $, WebView, wv;

  $ = require("../proj/web/lib/jquery-2.1.3.min.js");

  WebView = (function() {
    WebView.prototype.ipc = require("ipc");

    WebView.prototype.fs = require("fs");

    WebView.prototype.shell = require("shell");

    function WebView() {
      1;
    }

    WebView.prototype.set_event = function() {
      this.ipc.on("keydown", (function(_this) {
        return function(selector, keyCode) {
          return _this.set_keydown_event(selector, keyCode);
        };
      })(this));
      this.ipc.on("mouseclick", (function(_this) {
        return function(selector) {
          return $(selector).click();
        };
      })(this));
      this.ipc.on("css", (function(_this) {
        return function(selector, prop, val) {
          return $(selector).css(prop, val);
        };
      })(this));
      return this.ipc.on("set val", (function(_this) {
        return function(selector, val) {
          return $(selector).val(val);
        };
      })(this));
    };

    WebView.prototype.set_keydown_event = function(selector, keyCode) {
      var e;
      $(selector).focus();
      e = $.Event("keypress");
      e.which = keyCode;
      $(selector).val($(selector).val() + String.fromCharCode(e.which));
      return $(selector).trigger(e);
    };

    WebView.prototype.start = function() {
      return 1;
    };

    return WebView;

  })();

  wv = new WebView();

  wv.set_event();

  console.log("new webview preload finished");

}).call(this);

//# sourceMappingURL=WebView.js.map
