// Generated by CoffeeScript 1.9.3
(function() {
  this.compiler = require('child_process').fork('./contents/nodejs/Compiler.js');

  this.compiler.on("message", (function(_this) {
    return function(msg) {
      return console.log(msg);
    };
  })(this));

  this.App = require("./proj/node/NodeProjApp.js");

  this.a = new this.App();

}).call(this);
