// Generated by CoffeeScript 1.8.0
(function() {
  this.AtomApp = (function() {
    AtomApp.prototype.reload_ = 1;

    function AtomApp() {
      this.init();
    }

    AtomApp.prototype.init = function() {
      return this.fs = require("fs");
    };

    AtomApp.prototype.start = function() {
      if (this.reload_) {
        return this.auto_reload();
      }
    };

    AtomApp.prototype.auto_reload = function() {
      return this.fs.watch("contents", (function(_this) {
        return function(e, filename) {
          if (filename.match(/\.(html)|(js)|(css)$/)) {
            return location.reload();
          } else {
            return 1;
          }
        };
      })(this));
    };

    return AtomApp;

  })();

  $((function(_this) {
    return function() {
      _this.aa = new _this.AtomApp;
      return aa.start();
    };
  })(this));

}).call(this);

//# sourceMappingURL=AtomApp.js.map
