// Generated by CoffeeScript 1.9.2
(function() {
  $((function(_this) {
    return function() {
      _this.AtomProjApp = require("./AtomProjApp.js");
      return _this.aa = new _this.AtomProjApp();
    };
  })(this));

  1;

}).call(this);

//# sourceMappingURL=main.js.map
