// Generated by CoffeeScript 1.9.3
(function() {
  $((function(_this) {
    return function() {
      _this.AtomProjApp = require("./proj/atom/AtomProjApp.js");
      return _this.aa = new _this.AtomProjApp();
    };
  })(this));

}).call(this);
