// Generated by CoffeeScript 1.9.0
(function() {
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  this.WebClient = (function(_super) {
    __extends(WebClient, _super);

    function WebClient() {
      return WebClient.__super__.constructor.apply(this, arguments);
    }

    return WebClient;

  })(this.CommonJsAroundProtocol);

}).call(this);

//# sourceMappingURL=WebClient.js.map
